---
- name: install common dependencies
  become: yes
  pkgng: name={{item}} state=present
  with_items:
    - ca_root_nss
    - git-lite
    - curl

- name: install ntp
  become: yes
  pkgng: name=ntp state=present

- name: enable ntpd in rc.conf
  become: yes
  lineinfile:
    dest: /etc/rc.conf
    line: ntpd_enable=YES
    state: present
  register: ntpd_enabled

- name: set ntp time
  become: yes
  command: ntpd -qg
  when: ntpd_enabled.changed

- name: enable ntpd
  become: yes
  service: name=ntpd enabled=yes state=started

- name: install pip
  become: yes
  shell: curl https://bootstrap.pypa.io/get-pip.py | /usr/local/bin/python3.6
  args:
    creates: /usr/local/bin/pip3.6
    warn: no

- name: ensure lang
  lineinfile:
    path: "{{ansible_env['HOME']}}/.profile"
    line: "LANG=en_US.UTF-8; export LANG"

- name: install s6
  become: yes
  pkgng: name={{item}} state=present
  with_items:
    - execline
    - s6

- name: enable s6 in rc.conf
  become: yes
  lineinfile:
    dest: /etc/rc.conf
    line: s6_enable=YES
    state: present
  register: s6_enabled

- name: enable s6
  become: yes
  service: name=s6 enabled=yes state=started
  when: s6_enabled.changed

- name: setup periodic logging
  become: yes
  lineinfile:
    dest: /etc/periodic.conf
    line: "{{item}}"
    state: present
  with_items:
    - daily_output="/var/log/daily.log"
    - weekly_output="/var/log/weekly.log"
    - monthly_output="/var/log/monthly.log"
