---
- import_tasks: deinstall.yml

- name: install dnscrypt-proxy
  become: yes
  pkgng: name=dnscrypt-proxy2 state=present

- name: configure dnscrypt-proxy
  become: yes
  copy:
    src: dnscrypt-proxy.toml
    dest: /usr/local/etc/dnscrypt-proxy.toml
  notify:
    - restart dnscrypt-proxy

- name: ensure dnscrypt-proxy service directory
  become: yes
  file:
    path: /var/service/dnscrypt-proxy
    state: directory

- name: install dnscrypt-proxy service
  become: yes
  copy:
    src: run
    dest: /var/service/dnscrypt-proxy/run
    mode: 0555
  notify:
    - rescan s6
