---
- name: ensure blocklist directory
  become: yes
  file:
    path: "{{item}}"
    owner: nobody
    group: nobody
    state: directory
  with_items:
    - /usr/local/etc/unbound/blocklist

- name: install blocklist
  become: yes
  copy:
    src: "blocklist/{{item}}"
    dest: "/usr/local/etc/unbound/blocklist/{{item}}"
    owner: nobody
    group: nobody
  with_items:
    - blocklist.txt
    - generate.sh
  register: blocklist_installed

- name: generate initial blocklist
  become: yes
  command: |
    sh /usr/local/etc/unbound/blocklist/generate.sh \
        --blocklist /usr/local/etc/unbound/blocklist/blocklist.txt \
        --output /usr/local/etc/unbound/blocklist/blocklist.conf
  when: blocklist_installed.changed
  notify:
    - restart unbound

- name: chown initial blocklist
  become: yes
  file:
    path: /usr/local/etc/unbound/blocklist/blocklist.conf
    owner: nobody
    group: nobody

- name: setup blocklist periodic
  become: yes
  copy:
    src: "blocklist/periodic"
    dest: "/usr/local/etc/periodic/daily/900.blocklist"
    mode: 0555
