---
- name: install unbound
  become: yes
  pkgng: name=unbound state=present

- name: configure unbound
  become: yes
  copy:
    src: unbound/unbound.conf
    dest: /usr/local/etc/unbound/unbound.conf
  notify:
    - restart unbound

- name: ensure unbound service directory
  become: yes
  file:
    path: /var/service/unbound
    state: directory

- name: install unbound service
  become: yes
  copy:
    src: unbound/run
    dest: /var/service/unbound/run
    mode: 0555
  notify:
    - rescan s6
