---
- name: install unbound
  become: yes
  pkgng: name=unbound state=present

- name: configure unbound
  become: yes
  copy:
    src: unbound/unbound.conf
    dest: /usr/local/etc/unbound/unbound.conf
    owner: unbound
    group: wheel
  notify:
    - restart unbound

- name: configure unbound named.cache
  become: yes
  get_url:
    url: https://www.internic.net/domain/named.cache
    dest: /usr/local/etc/unbound/named.cache
    owner: unbound
    group: wheel

- name: configure unbound dlv.isc.org.key
  become: yes
  get_url:
    url: https://ftp.isc.org/www/dlv/dlv.isc.org.key
    dest: /usr/local/etc/unbound/dlv.isc.org.key
    owner: unbound
    group: wheel

- name: configure unbound root.key
  become: yes
  become_user: unbound
  command: /usr/local/sbin/unbound-anchor -a /usr/local/etc/unbound/root.key
  args:
    creates: /usr/local/etc/unbound/root.key
  register: unbound_root_key
  failed_when: unbound_root_key.rc > 1

- name: ensure unbound service directory
  become: yes
  file:
    path: /var/service/unbound
    state: directory

- name: install unbound service
  become: yes
  copy:
    src: unbound/run
    dest: /var/service/unbound/run
    mode: 0555
  notify:
    - rescan s6
