server_names = ['cloudflare']
listen_addresses = ['127.0.0.1:5353']
max_clients = 250

ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true

require_dnssec = false
require_nolog = true
require_nofilter = true

force_tcp = false
timeout = 2500
cert_refresh_delay = 240

fallback_resolver = '8.8.8.8:53'
ignore_system_dns = true
block_ipv6 = false

cache = true
cache_size = 512
cache_min_ttl = 600
cache_max_ttl = 86400

[sources.public-resolvers]
urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md']
cache_file = 'public-resolvers.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 72
prefix = ''
