server_names = ['cloudflare', 'cloudflare-ipv6']
listen_addresses = ['127.0.0.1:5353']
max_clients = 250

ipv4_servers = true
ipv6_servers = true
dnscrypt_servers = true
doh_servers = true

require_dnssec = true
require_nolog = true
require_nofilter = true

force_tcp = false
timeout = 2500
cert_refresh_delay = 240

fallback_resolver = '1.1.1.1:53'
ignore_system_dns = true
block_ipv6 = false

cache = false

[sources.public-resolvers]
urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md']
cache_file = 'public-resolvers.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 72
prefix = ''
