---
- name: delete dnscrypt-proxy service directories
  become: yes
  file:
    dest: "/var/service/dnscrypt-proxy"
    state: absent
  notify:
    - rescan s6

- name: remove dnscrypt-proxy
  become: yes
  pkgng:
    name: dnscrypt-proxy2
    state: absent

- name: flush handler
  become: yes
  meta: flush_handlers
